### ISSUE TITLE
Login and fast logout

### ISSUE THREAD

**Issue by marcoz70** [chris1111/Fix-Old-NVIDIA-macOS-Mojave-macOS-Catalina#2]
Hi, i have installed your fix for an Old Nvidia card on Catalina beta 5. I reach the login, i enter the password and all seems to go fine but after few second i read the error gIOScreenLockState 3 and i throw out to the login again.
Any ideas?

Marco

**Comment by chris1111** [comment]
never see that ? But you do not even say what graphics card you use and on which motherboard

**Comment by marcoz70** [comment]
My graphic card is nVidia 740GT and now i can't boot in the system because after the Apple logo hangs on white screen with cursor.
I use the latest clover bootloader.

**Comment by chris1111** [comment]
nVidia 740GT is not support by this patch.
Support: GeForce 5xx, 4xx, 2xx, 8600M(GT)/8800M(GT), 9400M/9600M(GT), 320M/330M

**Comment by marcoz70** [comment]
Do you know if possible in the future?

**Comment by chris1111** [comment]
> Do you know if possible in the future?

Not possible your card works with the  Nvidia web Drivers; so it support on macOS High Sierra
